# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee1ae5cf46534ce180d078ad079b732b6cb209e6c956a9d7e67139ff9a668625d5228aaa3592f3e28f6ae64c2b2131ef353ed84e52e6dbca6b5cf37b7ecc0d81

test:
  secret_key_base: 976d7d86e495bd970d61b75a8dd10992d7feb64e814915731b2b0051dcee8e1b6abd38a9320b145eeac25911957a9d7f37acc58d4726f0fd72db04678289969c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
